name: Build and Deploy Jekyll with BibTeX

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2       # match your local Ruby version
          bundler-cache: true

      # 3️⃣ Install gems from Gemfile
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # 4️⃣ Build the Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # 5️⃣ Deploy _site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # optional: you can set branch: gh-pages if needed
