name: Build and Deploy Quarto Book with Jekyll

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Specify the Ruby version for Jekyll

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          R-version: '4.4.1'

      - name: Install Quarto
        run: |
          install.packages('remotes')
          remotes::install_github('quarto-dev/quarto-r')

      - name: Render the Quarto book
        run: |
          quarto render documents/BoosStefanskiQMD/

      - name: Build Jekyll Site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documents/BoosStefanskiQMD/_book  # Adjust if necessary
