name: Render Quarto Book

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          version: 'latest'

      - name: Cache Quarto CLI
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/quarto
          key: ${{ runner.os }}-quarto-${{ hashFiles('quarto-version') }}
          restore-keys: ${{ runner.os }}-quarto-

      - name: Install Quarto
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.313/quarto-1.2.313-linux-amd64.deb
          sudo dpkg -i quarto-1.2.313-linux-amd64.deb

      - name: Cache LaTeX installation
        uses: actions/cache@v2
        with:
          path: /usr/share/texlive
          key: ${{ runner.os }}-latex-${{ hashFiles('latex-version') }}
          restore-keys: ${{ runner.os }}-latex-

      - name: Install LaTeX
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-xetex

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("jsonlite", "rmarkdown", "kableExtra", "numDeriv"), dependencies = TRUE, repos = "https://cloud.r-project.org")'

      - name: Load R packages
        run: |
          Rscript -e 'library(jsonlite); library(rmarkdown); library(kableExtra); library(numDeriv)'

      - name: Render Quarto project
        run: |
          quarto render documents/BoosStefanskiQMD

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documents/BoosStefanskiQMD/_site
