name: Render Quarto Book

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
  workflow_dispatch:


jobs:
  render-quarto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          version: 'latest'  # Specify R version if needed

      - name: Install dependencies
        run: |
          install.packages("quarto")
          # Install any other necessary packages

      - name: Render Quarto project
        run: |
          quarto render documents/BoosStefanskiQMD/_quarto.yml --output-dir documents/BoosStefanskiQMD/_site

      - name: Deploy Quarto site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documents/BoosStefanskiQMD/_site  # Adjust this if necessary
